### ISSUE TITLE
Reformat documentation to use triple-slash doxygen format.

### ISSUE THREAD

**Issue by Dimi1010** [seladb/PcapPlusPlus#1658]
## Rationale:
- Reduced line bloat. Each documentation block is 2 lines shorter on average.
This can compound to over 100 lines on some of the larger files. (e.g. "IPAddress.h")
- Makes usages of comment blocks /* */ easier to manage during refactoring, as they won't be terminated early if there are documentation comments inside them.

## Progress summary:
- [x] Common++
  - [x] Namespace and file docs (#1647)
  - [x] Class and Struct docs (#1647)
  - [x] Enums (unsure if the enums are formatted already)
- [x] Packet++
  - [x] Namespace and file docs (#1659)
  - [x] Class and Struct docs (#1659)
  - [x] Enums (#1659)
- [x] Pcap++
  - [x] Namespace and file docs (#1660)
  - [x] Class and Struct docs (#1660)
  - [x] Enums (#1660)

**Comment by Dimi1010** [comment]
Discontinued due to issues with #1659 .

**Comment by seladb** [comment]
@Dimi1010 I think we can close this issue, please let me know if you think otherwise
